-- Production schema is managed by:
-- supabase/migrations/20260608184500_final_production_minus_payments.sql
--
-- This file is kept only so older stage notes that referenced
-- supabase/profiles.sql do not point to a missing path.
